#!/usr/bin/env python3
from __future__ import annotations

import argparse
import getpass
import grp
import ipaddress
import os
import shlex
import shutil
import subprocess
from pathlib import Path
from urllib.parse import urlparse, urlunparse


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate and optionally install server bootstrap assets for Newsletter Curator."
    )
    parser.add_argument("--repo-dir", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--uv-bin", default=shutil.which("uv") or "uv")
    parser.add_argument("--config-path", type=Path, default=None)
    parser.add_argument(
        "--app-host",
        "--admin-host",
        dest="app_host",
        default=os.getenv("CURATOR_APP_HOST", os.getenv("CURATOR_ADMIN_HOST", "127.0.0.1")),
        help="HTTP app bind host. --admin-host remains accepted as a deprecated alias.",
    )
    parser.add_argument(
        "--app-port",
        "--admin-port",
        dest="app_port",
        type=int,
        default=int(os.getenv("CURATOR_APP_PORT", os.getenv("CURATOR_ADMIN_PORT", "8080"))),
        help="HTTP app bind port. --admin-port remains accepted as a deprecated alias.",
    )
    parser.add_argument("--admin-token", default=os.getenv("CURATOR_ADMIN_TOKEN", ""))
    parser.add_argument(
        "--mcp-token",
        default=os.getenv("CURATOR_MCP_TOKEN", ""),
        help=(
            "Bearer token for the remote HTTP /mcp endpoint. "
            "Defaults to CURATOR_MCP_TOKEN, and falls back to --admin-token when omitted."
        ),
    )
    parser.add_argument(
        "--debug-log-token",
        default=os.getenv("CURATOR_DEBUG_LOG_TOKEN", ""),
        help=(
            "Dedicated bearer or URL token for the read-only /debug/logs endpoint. "
            "Leave empty to keep the endpoint disabled."
        ),
    )
    parser.add_argument("--openai-api-key", default=os.getenv("OPENAI_API_KEY", ""))
    parser.add_argument("--buttondown-api-key", default=os.getenv("BUTTONDOWN_API_KEY", ""))
    parser.add_argument("--public-base-url", default=os.getenv("CURATOR_PUBLIC_BASE_URL", ""))
    parser.add_argument("--cron-timezone", default="")
    parser.add_argument("--daily-schedule", default="0 13 * * *")
    parser.add_argument("--cron-log-file", type=Path, default=None)
    parser.add_argument("--debug-log-file", type=Path, default=None)
    parser.add_argument("--logrotate-file", type=Path, default=None)
    parser.add_argument("--logrotate-dir", type=Path, default=Path("/etc/logrotate.d"))
    parser.add_argument("--logrotate-rotate-count", type=int, default=7)
    parser.add_argument("--install-logrotate", action="store_true")
    parser.add_argument("--service-name", default="newsletter-curator-admin")
    parser.add_argument("--install-crontab", action="store_true")
    parser.add_argument(
        "--install-systemd-user",
        action="store_true",
        help="Opt in to installing and starting the admin app systemd --user service.",
    )
    parser.add_argument("--enable-linger", action="store_true")
    parser.add_argument("--linger-user", default=os.getenv("USER") or getpass.getuser())
    return parser.parse_args()


def quote(value: str | Path) -> str:
    return shlex.quote(str(value))


def write_file(path: Path, content: str, mode: int = 0o644) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(mode)


def read_env_assignments(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    assignments: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        assignments[key.strip()] = value
    return assignments


def build_env_file(
    *,
    repo_dir: Path,
    config_path: Path,
    app_host: str,
    app_port: int,
    admin_token: str,
    mcp_token: str,
    debug_log_token: str,
    debug_log_path: Path,
    admin_service_name: str,
    openai_api_key: str,
    buttondown_api_key: str,
    public_base_url: str,
) -> str:
    return "\n".join(
        [
            "# Generated by scripts/bootstrap_server.py",
            f"NEWSLETTER_CONFIG={config_path}",
            f"CURATOR_APP_HOST={app_host}",
            f"CURATOR_APP_PORT={app_port}",
            f"CURATOR_ADMIN_TOKEN={admin_token}",
            f"CURATOR_MCP_TOKEN={mcp_token}",
            f"CURATOR_DEBUG_LOG_TOKEN={debug_log_token}",
            f"CURATOR_DEBUG_LOG_PATH={debug_log_path}",
            f"CURATOR_ADMIN_SERVICE_NAME={admin_service_name}",
            "CURATOR_PAUSE_ADMIN_DURING_DAILY=1",
            f"OPENAI_API_KEY={openai_api_key}",
            f"BUTTONDOWN_API_KEY={buttondown_api_key}",
            f"CURATOR_PUBLIC_BASE_URL={public_base_url}",
            f"PATH={os.getenv('PATH', '/usr/local/bin:/usr/bin:/bin')}",
            "",
        ]
    )


def _is_direct_access_hostname(hostname: str) -> bool:
    normalized = str(hostname or "").strip().lower()
    if not normalized:
        return False
    if normalized == "localhost":
        return True
    try:
        ipaddress.ip_address(normalized)
    except ValueError:
        return False
    return True


def normalize_public_base_url(public_base_url: str, app_port: int) -> str:
    configured = str(public_base_url or "").strip()
    if not configured:
        return ""
    parsed = urlparse(configured)
    if not parsed.scheme or not parsed.netloc or parsed.port is not None:
        return configured.rstrip("/")

    default_port = 80 if parsed.scheme == "http" else 443 if parsed.scheme == "https" else None
    if app_port == default_port or not _is_direct_access_hostname(parsed.hostname or ""):
        return configured.rstrip("/")

    hostname = str(parsed.hostname or "").strip()
    host_display = f"[{hostname}]" if ":" in hostname else hostname
    userinfo = ""
    if parsed.username:
        userinfo = parsed.username
        if parsed.password:
            userinfo += f":{parsed.password}"
        userinfo += "@"
    return urlunparse(parsed._replace(netloc=f"{userinfo}{host_display}:{app_port}")).rstrip("/")


def public_base_url_warning(public_base_url: str, app_port: int) -> str:
    configured = str(public_base_url or "").strip()
    if not configured:
        return ""
    parsed = urlparse(configured)
    if not parsed.scheme or not parsed.netloc:
        return ""
    if parsed.port is not None:
        return ""
    if app_port in {80, 443}:
        return ""
    if _is_direct_access_hostname(parsed.hostname or ""):
        return ""
    return (
        "Warning: --public-base-url has no explicit port while --app-port is set to "
        f"{app_port}. This is correct only if your public origin is behind a reverse proxy on "
        "the scheme default port. Otherwise subscriber login links and tracking links will omit "
        f":{app_port}."
    )


def build_runner_script(*, repo_dir: Path, env_file: Path, uv_bin: str, entrypoint: str) -> str:
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            f"cd {quote(repo_dir)}",
            "set -a",
            f"source {quote(env_file)}",
            "set +a",
            "",
            f'if [[ -z "${{OPENAI_API_KEY:-}}" ]]; then',
            f'  echo "error: OPENAI_API_KEY is empty after loading {quote(env_file)}" >&2',
            "  exit 1",
            "fi",
            f'if [[ -z "${{BUTTONDOWN_API_KEY:-}}" ]]; then',
            f'  echo "error: BUTTONDOWN_API_KEY is empty after loading {quote(env_file)}" >&2',
            "  exit 1",
            "fi",
            f"exec {quote(uv_bin)} run python {quote(entrypoint)} \"$@\"",
            "",
        ]
    )


def build_logrotate_config(
    *,
    debug_log_path: Path,
    rotate_count: int,
    owner: str,
    group: str,
) -> str:
    return "\n".join(
        [
            f"{debug_log_path} {{",
            "    daily",
            f"    rotate {max(1, int(rotate_count))}",
            "    compress",
            "    missingok",
            "    notifempty",
            f"    create 0600 {owner} {group}",
            "}",
            "",
        ]
    )


def build_daily_runner_script(*, repo_dir: Path, env_file: Path, uv_bin: str) -> str:
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            f"cd {quote(repo_dir)}",
            "set -a",
            f"source {quote(env_file)}",
            "set +a",
            "",
            f'if [[ -z "${{OPENAI_API_KEY:-}}" ]]; then',
            f'  echo "error: OPENAI_API_KEY is empty after loading {quote(env_file)}" >&2',
            "  exit 1",
            "fi",
            f'if [[ -z "${{BUTTONDOWN_API_KEY:-}}" ]]; then',
            f'  echo "error: BUTTONDOWN_API_KEY is empty after loading {quote(env_file)}" >&2',
            "  exit 1",
            "fi",
            "",
            'should_manage_admin=0',
            'if [[ "${CURATOR_PAUSE_ADMIN_DURING_DAILY:-0}" =~ ^(1|true|yes|on)$ ]] && [[ -n "${CURATOR_ADMIN_SERVICE_NAME:-}" ]]; then',
            "  should_manage_admin=1",
            "fi",
            "",
            "admin_resumed=0",
            "resume_admin_service() {",
            '  if [[ "$should_manage_admin" -ne 1 ]] || [[ "$admin_resumed" -eq 1 ]]; then',
            "    return 0",
            "  fi",
            "  admin_resumed=1",
            '  systemctl --user start "$CURATOR_ADMIN_SERVICE_NAME" || \\',
            '    echo "warning: failed to restart admin service $CURATOR_ADMIN_SERVICE_NAME" >&2',
            "}",
            "",
            "handle_interrupt() {",
            "  resume_admin_service",
            "  exit 130",
            "}",
            "",
            "handle_terminate() {",
            "  resume_admin_service",
            "  exit 143",
            "}",
            "",
            "trap resume_admin_service EXIT",
            "trap handle_interrupt INT",
            "trap handle_terminate TERM",
            "",
            "pause_admin_service() {",
            '  if [[ "$should_manage_admin" -ne 1 ]]; then',
            "    return 0",
            "  fi",
            '  systemctl --user stop "$CURATOR_ADMIN_SERVICE_NAME" || \\',
            '    echo "warning: failed to stop admin service $CURATOR_ADMIN_SERVICE_NAME; continuing daily pipeline" >&2',
            "}",
            "",
            "pause_admin_service",
            "",
            "set +e",
            f"{quote(uv_bin)} run python daily_pipeline.py \"$@\"",
            "pipeline_status=$?",
            "set -e",
            "exit \"$pipeline_status\"",
            "",
        ]
    )


def build_cron_file(
    *,
    cron_timezone: str,
    daily_schedule: str,
    log_file: Path,
    daily_script: Path,
) -> str:
    lines = [
        "SHELL=/bin/bash",
        f"PATH={os.getenv('PATH', '/usr/local/bin:/usr/bin:/bin')}",
    ]
    if str(cron_timezone).strip():
        lines.append(f"CRON_TZ={cron_timezone}")
    lines.extend(
        [
            "",
            f"{daily_schedule} {quote(daily_script)} >> {quote(log_file)} 2>&1",
            "",
        ]
    )
    return "\n".join(lines)


def build_systemd_service(
    *,
    service_name: str,
    repo_dir: Path,
    env_file: Path,
    admin_script: Path,
) -> str:
    return "\n".join(
        [
            "[Unit]",
            f"Description={service_name}",
            "After=network-online.target",
            "Wants=network-online.target",
            "",
            "[Service]",
            "Type=simple",
            f"WorkingDirectory={repo_dir}",
            f"EnvironmentFile={env_file}",
            f"ExecStart={admin_script}",
            "Restart=always",
            "RestartSec=5",
            "",
            "[Install]",
            "WantedBy=default.target",
            "",
        ]
    )


def install_systemd_user_service(service_file: Path, service_name: str) -> None:
    target_dir = Path.home() / ".config" / "systemd" / "user"
    target_dir.mkdir(parents=True, exist_ok=True)
    target_path = target_dir / f"{service_name}.service"
    write_file(target_path, service_file.read_text(encoding="utf-8"))
    subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
    subprocess.run(["systemctl", "--user", "enable", service_name], check=True)
    subprocess.run(["systemctl", "--user", "restart", service_name], check=True)


def enable_user_linger(user_name: str) -> None:
    subprocess.run(["loginctl", "enable-linger", user_name], check=True)


def install_crontab(cron_file: Path) -> None:
    subprocess.run(["crontab", str(cron_file)], check=True)


def install_logrotate_config(logrotate_file: Path, target_dir: Path, service_name: str) -> Path:
    target_dir.mkdir(parents=True, exist_ok=True)
    target_path = target_dir / service_name
    write_file(target_path, logrotate_file.read_text(encoding="utf-8"))
    return target_path


def main() -> None:
    args = parse_args()
    if not str(args.mcp_token or "").strip():
        args.mcp_token = args.admin_token
    normalized_public_base_url = normalize_public_base_url(args.public_base_url, args.app_port)
    repo_dir = args.repo_dir.resolve()
    output_dir = (
        args.output_dir.resolve()
        if args.output_dir is not None
        else (repo_dir / "deploy" / "generated").resolve()
    )
    config_path = (args.config_path or (repo_dir / "config.yaml")).resolve()
    log_file = (args.cron_log_file or (repo_dir / "deploy" / "generated" / "cron.log")).resolve()

    output_dir.mkdir(parents=True, exist_ok=True)

    env_file = output_dir / "newsletter-curator.env"
    existing_env = read_env_assignments(env_file)
    openai_api_key = str(args.openai_api_key or "").strip() or existing_env.get("OPENAI_API_KEY", "")
    buttondown_api_key = (
        str(args.buttondown_api_key or "").strip() or existing_env.get("BUTTONDOWN_API_KEY", "")
    )
    debug_log_token = (
        str(args.debug_log_token or "").strip() or existing_env.get("CURATOR_DEBUG_LOG_TOKEN", "")
    )
    debug_log_path = (
        args.debug_log_file.resolve()
        if args.debug_log_file is not None
        else Path(
            existing_env.get(
                "CURATOR_DEBUG_LOG_PATH",
                str((output_dir / "debug.ndjson").resolve()),
            )
        ).expanduser().resolve()
    )
    logrotate_file = (
        args.logrotate_file.resolve()
        if args.logrotate_file is not None
        else (output_dir / "newsletter-curator.logrotate").resolve()
    )
    logrotate_owner = getpass.getuser()
    logrotate_group = grp.getgrgid(os.getgid()).gr_name
    admin_script = output_dir / "start_admin_server.sh"
    daily_script = output_dir / "run_daily_pipeline.sh"
    fetch_gmail_script = output_dir / "run_fetch_gmail.sh"
    fetch_sources_script = output_dir / "run_fetch_sources.sh"
    deliver_script = output_dir / "run_deliver_digest.sh"
    cron_file = output_dir / "newsletter-curator.cron"
    service_file = output_dir / f"{args.service_name}.service"

    write_file(
        env_file,
        build_env_file(
            repo_dir=repo_dir,
            config_path=config_path,
            app_host=args.app_host,
            app_port=args.app_port,
            admin_token=args.admin_token,
            mcp_token=args.mcp_token,
            debug_log_token=debug_log_token,
            debug_log_path=debug_log_path,
            admin_service_name=args.service_name,
            openai_api_key=openai_api_key,
            buttondown_api_key=buttondown_api_key,
            public_base_url=normalized_public_base_url,
        ),
        mode=0o600,
    )
    write_file(
        admin_script,
        build_runner_script(
            repo_dir=repo_dir,
            env_file=env_file,
            uv_bin=args.uv_bin,
            entrypoint="admin_app.py",
        ),
        mode=0o700,
    )
    write_file(
        daily_script,
        build_daily_runner_script(
            repo_dir=repo_dir,
            env_file=env_file,
            uv_bin=args.uv_bin,
        ),
        mode=0o700,
    )
    write_file(
        fetch_gmail_script,
        build_runner_script(
            repo_dir=repo_dir,
            env_file=env_file,
            uv_bin=args.uv_bin,
            entrypoint="fetch_gmail.py",
        ),
        mode=0o700,
    )
    write_file(
        fetch_sources_script,
        build_runner_script(
            repo_dir=repo_dir,
            env_file=env_file,
            uv_bin=args.uv_bin,
            entrypoint="fetch_sources.py",
        ),
        mode=0o700,
    )
    write_file(
        deliver_script,
        build_runner_script(
            repo_dir=repo_dir,
            env_file=env_file,
            uv_bin=args.uv_bin,
            entrypoint="deliver_digest.py",
        ),
        mode=0o700,
    )
    write_file(
        logrotate_file,
        build_logrotate_config(
            debug_log_path=debug_log_path,
            rotate_count=args.logrotate_rotate_count,
            owner=logrotate_owner,
            group=logrotate_group,
        ),
        mode=0o644,
    )
    write_file(
        cron_file,
        build_cron_file(
            cron_timezone=args.cron_timezone,
            daily_schedule=args.daily_schedule,
            log_file=log_file,
            daily_script=daily_script,
        ),
        mode=0o600,
    )
    write_file(
        service_file,
        build_systemd_service(
            service_name=args.service_name,
            repo_dir=repo_dir,
            env_file=env_file,
            admin_script=admin_script,
        ),
    )

    if args.install_crontab:
        install_crontab(cron_file)
    installed_logrotate_path: Path | None = None
    if args.install_logrotate:
        installed_logrotate_path = install_logrotate_config(
            logrotate_file,
            args.logrotate_dir.resolve(),
            args.service_name,
        )
    if args.install_systemd_user:
        install_systemd_user_service(service_file, args.service_name)
    if args.enable_linger:
        enable_user_linger(args.linger_user)

    print("Generated deployment assets:")
    for path in [
        env_file,
        admin_script,
        daily_script,
        fetch_gmail_script,
        fetch_sources_script,
        deliver_script,
        logrotate_file,
        cron_file,
        service_file,
    ]:
        print(f"- {path}")

    print("")
    print("Verification:")
    print(f"- Admin server script: {admin_script}")
    print(f"- Cron file: {cron_file}")
    print(f"- Log file: {log_file}")
    print(f"- Debug log file: {debug_log_path}")
    print(f"- Logrotate config: {logrotate_file}")
    if installed_logrotate_path is not None:
        print(f"- Installed logrotate config: {installed_logrotate_path}")
    if args.install_systemd_user:
        print("- Admin app service installed and restarted. Check: systemctl --user status "
              f"{args.service_name}")
    else:
        print("- Admin app not started by default. Pass --install-systemd-user to install "
              "and start it.")
    print("- If you passed --install-crontab, check: crontab -l")
    base_url_warning = public_base_url_warning(normalized_public_base_url, args.app_port)
    if base_url_warning:
        print(f"- {base_url_warning}")


if __name__ == "__main__":
    main()
