#!/usr/bin/env python3
from __future__ import annotations

import argparse
import getpass
import os
import shlex
import shutil
import subprocess
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate and optionally install server bootstrap assets for Newsletter Curator."
    )
    parser.add_argument("--repo-dir", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--uv-bin", default=shutil.which("uv") or "uv")
    parser.add_argument("--config-path", type=Path, default=None)
    parser.add_argument("--admin-host", default="127.0.0.1")
    parser.add_argument("--admin-port", type=int, default=8080)
    parser.add_argument("--admin-token", default=os.getenv("CURATOR_ADMIN_TOKEN", ""))
    parser.add_argument("--openai-api-key", default=os.getenv("OPENAI_API_KEY", ""))
    parser.add_argument("--public-base-url", default=os.getenv("CURATOR_PUBLIC_BASE_URL", ""))
    parser.add_argument("--cron-timezone", default="")
    parser.add_argument("--daily-schedule", default="30 14 * * *")
    parser.add_argument("--cron-log-file", type=Path, default=None)
    parser.add_argument("--service-name", default="newsletter-curator-admin")
    parser.add_argument("--install-crontab", action="store_true")
    parser.add_argument("--install-systemd-user", action="store_true")
    parser.add_argument("--enable-linger", action="store_true")
    parser.add_argument("--linger-user", default=os.getenv("USER") or getpass.getuser())
    return parser.parse_args()


def quote(value: str | Path) -> str:
    return shlex.quote(str(value))


def write_file(path: Path, content: str, mode: int = 0o644) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(mode)


def build_env_file(
    *,
    repo_dir: Path,
    config_path: Path,
    admin_host: str,
    admin_port: int,
    admin_token: str,
    openai_api_key: str,
    public_base_url: str,
) -> str:
    return "\n".join(
        [
            "# Generated by scripts/bootstrap_server.py",
            f"NEWSLETTER_CONFIG={config_path}",
            f"CURATOR_ADMIN_HOST={admin_host}",
            f"CURATOR_ADMIN_PORT={admin_port}",
            f"CURATOR_ADMIN_TOKEN={admin_token}",
            f"OPENAI_API_KEY={openai_api_key}",
            f"CURATOR_PUBLIC_BASE_URL={public_base_url}",
            f"PATH={os.getenv('PATH', '/usr/local/bin:/usr/bin:/bin')}",
            "",
        ]
    )


def build_runner_script(*, repo_dir: Path, env_file: Path, uv_bin: str, entrypoint: str) -> str:
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            f"cd {quote(repo_dir)}",
            "set -a",
            f"source {quote(env_file)}",
            "set +a",
            f"exec {quote(uv_bin)} run python {quote(entrypoint)}",
            "",
        ]
    )


def build_cron_file(
    *,
    cron_timezone: str,
    daily_schedule: str,
    log_file: Path,
    daily_script: Path,
) -> str:
    lines = [
        "SHELL=/bin/bash",
        f"PATH={os.getenv('PATH', '/usr/local/bin:/usr/bin:/bin')}",
    ]
    if str(cron_timezone).strip():
        lines.append(f"CRON_TZ={cron_timezone}")
    lines.extend(
        [
            "",
            f"{daily_schedule} {quote(daily_script)} >> {quote(log_file)} 2>&1",
            "",
        ]
    )
    return "\n".join(lines)


def build_systemd_service(
    *,
    service_name: str,
    repo_dir: Path,
    env_file: Path,
    admin_script: Path,
) -> str:
    return "\n".join(
        [
            "[Unit]",
            f"Description={service_name}",
            "After=network-online.target",
            "Wants=network-online.target",
            "",
            "[Service]",
            "Type=simple",
            f"WorkingDirectory={repo_dir}",
            f"EnvironmentFile={env_file}",
            f"ExecStart={admin_script}",
            "Restart=always",
            "RestartSec=5",
            "",
            "[Install]",
            "WantedBy=default.target",
            "",
        ]
    )


def install_systemd_user_service(service_file: Path, service_name: str) -> None:
    target_dir = Path.home() / ".config" / "systemd" / "user"
    target_dir.mkdir(parents=True, exist_ok=True)
    target_path = target_dir / f"{service_name}.service"
    write_file(target_path, service_file.read_text(encoding="utf-8"))
    subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
    subprocess.run(["systemctl", "--user", "enable", service_name], check=True)
    subprocess.run(["systemctl", "--user", "restart", service_name], check=True)


def enable_user_linger(user_name: str) -> None:
    subprocess.run(["loginctl", "enable-linger", user_name], check=True)


def install_crontab(cron_file: Path) -> None:
    subprocess.run(["crontab", str(cron_file)], check=True)


def main() -> None:
    args = parse_args()
    repo_dir = args.repo_dir.resolve()
    output_dir = (
        args.output_dir.resolve()
        if args.output_dir is not None
        else (repo_dir / "deploy" / "generated").resolve()
    )
    config_path = (args.config_path or (repo_dir / "config.yaml")).resolve()
    log_file = (args.cron_log_file or (repo_dir / "deploy" / "generated" / "cron.log")).resolve()

    output_dir.mkdir(parents=True, exist_ok=True)

    env_file = output_dir / "newsletter-curator.env"
    admin_script = output_dir / "start_admin_server.sh"
    daily_script = output_dir / "run_daily_pipeline.sh"
    fetch_gmail_script = output_dir / "run_fetch_gmail.sh"
    fetch_sources_script = output_dir / "run_fetch_sources.sh"
    deliver_script = output_dir / "run_deliver_digest.sh"
    cron_file = output_dir / "newsletter-curator.cron"
    service_file = output_dir / f"{args.service_name}.service"

    write_file(
        env_file,
        build_env_file(
            repo_dir=repo_dir,
            config_path=config_path,
            admin_host=args.admin_host,
            admin_port=args.admin_port,
            admin_token=args.admin_token,
            openai_api_key=args.openai_api_key,
            public_base_url=args.public_base_url,
        ),
        mode=0o600,
    )
    write_file(
        admin_script,
        build_runner_script(
            repo_dir=repo_dir,
            env_file=env_file,
            uv_bin=args.uv_bin,
            entrypoint="admin_app.py",
        ),
        mode=0o700,
    )
    write_file(
        daily_script,
        build_runner_script(
            repo_dir=repo_dir,
            env_file=env_file,
            uv_bin=args.uv_bin,
            entrypoint="daily_pipeline.py",
        ),
        mode=0o700,
    )
    write_file(
        fetch_gmail_script,
        build_runner_script(
            repo_dir=repo_dir,
            env_file=env_file,
            uv_bin=args.uv_bin,
            entrypoint="fetch_gmail.py",
        ),
        mode=0o700,
    )
    write_file(
        fetch_sources_script,
        build_runner_script(
            repo_dir=repo_dir,
            env_file=env_file,
            uv_bin=args.uv_bin,
            entrypoint="fetch_sources.py",
        ),
        mode=0o700,
    )
    write_file(
        deliver_script,
        build_runner_script(
            repo_dir=repo_dir,
            env_file=env_file,
            uv_bin=args.uv_bin,
            entrypoint="deliver_digest.py",
        ),
        mode=0o700,
    )
    write_file(
        cron_file,
        build_cron_file(
            cron_timezone=args.cron_timezone,
            daily_schedule=args.daily_schedule,
            log_file=log_file,
            daily_script=daily_script,
        ),
        mode=0o600,
    )
    write_file(
        service_file,
        build_systemd_service(
            service_name=args.service_name,
            repo_dir=repo_dir,
            env_file=env_file,
            admin_script=admin_script,
        ),
    )

    if args.install_crontab:
        install_crontab(cron_file)
    if args.install_systemd_user:
        install_systemd_user_service(service_file, args.service_name)
    if args.enable_linger:
        enable_user_linger(args.linger_user)

    print("Generated deployment assets:")
    for path in [
        env_file,
        admin_script,
        daily_script,
        fetch_gmail_script,
        fetch_sources_script,
        deliver_script,
        cron_file,
        service_file,
    ]:
        print(f"- {path}")

    print("")
    print("Verification:")
    print(f"- Admin server script: {admin_script}")
    print(f"- Cron file: {cron_file}")
    print(f"- Log file: {log_file}")
    print("- If you passed --install-systemd-user, check: systemctl --user status "
          f"{args.service_name}")
    print("- If you passed --install-crontab, check: crontab -l")


if __name__ == "__main__":
    main()
